# Compiler Options
LTO_ENABLE = yes

# Hardware Features
AUDIO_SUPPORTED = no
RGBLIGHT_ENABLE = yes

SPLIT_KEYBOARD = yes
NKRO_ENABLE = yes

# Software Features
AUTO_SHIFT_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
